site_name: Apuntes del Profesor
theme:
  name: material
  language: es
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - content.code.copy
    - toc.integrate
plugins:
  - search
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.superfences
extra_javascript:
  - https://unpkg.com/thebe@latest/lib/index.js
  - https://cdn.jsdelivr.net/pyodide/v0.24.1/full/pyodide.js
extra:
  thebe:
    repository_url: ""
    kernel_name: python
nav:
  - Inicio: index.md
  - 1º ASIR:
      - GBBDD: asir/1/gbbdd/index.md
  - 2º ASIR:
      - SRI: asir/2/sri/index.md
  - 1º DAM:
      - BBDD: dam/1/bbdd/index.md
  - 2º DAM:
      - ACCDAT: dam/2/accdat/index.md
      - SGE: dam/2/sge/index.md
      - Proyecto: dam/2/proyecto/index.md
  - 2º DAW:
      - DWEC: daw/2/dwec/index.md
      - DIW: daw/2/diw/index.md
