# .github/workflows/deploy.yml
name: Deploy MkDocs

on:
  push:
    branches: [ gh-pages ]   # o master, seg√∫n tu rama

permissions:
  contents: write        # necesario para push a gh-pages

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # instala mkdocs y los plugins/tema que usa tu proyecto
          pip install mkdocs mkdocs-material mkdocs-jupyter

      - name: Build (sanity check)
        run: python -m mkdocs build --strict

      - name: Deploy to gh-pages
        # usar "python -m" evita problemas de PATH
        run: python -m mkdocs gh-deploy --force --message "Deployed by GitHub Actions"
